repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff (fix style issues)
        entry: ruff check --fix src/
        language: system
        types: [python]
        pass_filenames: false

