repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff (fix style issues)
        entry: ruff check --fix src/
        language: system
        pass_filenames: false
      - id: ruff-format
        name: ruff (format source code)
        entry: ruff format src/
        language: system
        pass_filenames: false
